#!/bin/bash

chmod 777 make.bat

cd src

cd bin   && rm -f *.exe *.dll *.ini && cd ..
cd lib   && rm -f *                 && cd ..

for str in `find . -name 'mk*' -type d `
do
  cd $str 
    rm -f Makefile* *.layout object_script*
    rm -f -d -r release debug
  cd ..
done

for str in `find . -name '*.cpp' -or -name '*.h'`
do
  dos2unix $str 2>/dev/null
done

dos2unix reqmake.bat  2>/dev/null
chmod 777 reqmake.bat