INCLUDEPATH += $${MKROOT}/src/3rdparty/qwt/src
LIBS        += -L$${MKROOT}/lib -lqwt$${SUFFIX_STR}

MKROOT_SHADOWED = $$shadowed($${PWD}$${MKROOT})
PRE_TARGETDEPS += $${MKROOT_SHADOWED}/lib/$${QMAKE_PREFIX_STATICLIB}qwt$${SUFFIX_STR}.$${QMAKE_EXTENSION_STATICLIB}
